baseURL = 'https://sqvrltastic.art/'
languageCode = 'en-us'
title = 'Sqvrltastic Art Archive'
theme = 'CleanGallery'
uglyURLs = true

[taxonomies]
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser]
  autoHeadingID = false

[params]
  description = "Hi, I'm sqvrltastic and I'm a digital artist. Welcome to my website! This is my main place for posting my artwork and sharing my thoughts."
  email = "sqvrltastic@gmail.com"
  preview = "https://sqvrltastic.art/images/feature-image.jpg"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "rss"  
  isHTML = false
  rel = "alternate"

[services]
  [services.rss]
    limit = 30