baseURL = 'https://sqvrltastic.github.io/'
languageCode = 'en-us'
title = 'Sqvrltastic art archive'
theme = 'CleanGallery'
uglyURLs = true
disableKinds = ["RSS"]
[taxonomies]
    category = "categories"
[markup.goldmark.renderer]
    unsafe = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false