baseURL = 'https://sqvrltastic.github.io/'
languageCode = 'en-us'
title = 'Sqvrltastic art archive'
theme = 'CleanGallery'
disableKinds = ["RSS"]
[taxonomies]
    category = "categories"
[markup.goldmark.renderer]
    unsafe = true